stages:
  - build

rust-latest:
  stage: build
  image: rust
  before_script:
    - apt-get update --yes
    - apt-get install --yes cmake
    - rustup component add rustfmt
    - rustup component add clippy
  script:
    - cargo fmt -- --check
    - cargo clippy --all-features -- -D warnings
    - cargo build --all-features --verbose
    - cargo test --all-features --verbose -- --test-threads=1